#!/usr/bin/env python3
"""Fix Guardar Estado DB: use the SQL from Preparar Upsert instead of hardcoded query."""
import json, urllib.request

N8N_API = 'http://127.0.0.1:5678/api/v1'
N8N_KEY = 'n8n_api_81f165083b2718697b35a9bfc5f75263ba645082b7fc6ff0'
WF_ID   = 'n8WMvyVqVj2Q9Ya0'

def api(method, path, data=None):
    url  = N8N_API + path
    body = json.dumps(data).encode() if data else None
    req  = urllib.request.Request(url, data=body, method=method,
           headers={'X-N8N-API-KEY': N8N_KEY, 'Content-Type':'application/json'})
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())

wf    = api('GET', f'/workflows/{WF_ID}')
nodes = {n['name']: n for n in wf['nodes']}

# Verify current state
g = nodes['Guardar Estado DB']
old_query = g['parameters']['query']
print('OLD query length:', len(old_query))
print('OLD query start:', old_query[:80])

# The fix: use the SQL generated by Preparar Upsert
new_query = '={{ $json.sql }}'
g['parameters']['query'] = new_query
print('\nNEW query:', new_query)

# Update the workflow
wf['nodes'] = list(nodes.values())
payload = {
    'name': wf['name'],
    'nodes': wf['nodes'],
    'connections': wf['connections'],
    'settings': wf.get('settings', {}),
    'staticData': wf.get('staticData')
}

api('POST', f'/workflows/{WF_ID}/deactivate')
result = api('PUT', f'/workflows/{WF_ID}', payload)
api('POST', f'/workflows/{WF_ID}/activate')

print('Active:', result.get('active', '?'))
print('FIXED: Guardar Estado DB now uses SQL from Preparar Upsert')

# Verify the fix
wf2 = api('GET', f'/workflows/{WF_ID}')
nodes2 = {n['name']: n for n in wf2['nodes']}
saved_query = nodes2['Guardar Estado DB']['parameters']['query']
print('Saved query:', saved_query)
assert saved_query == new_query, f'MISMATCH: {saved_query!r}'
print('VERIFIED OK')

# Also reset the stuck phone to 'nuevo' so we can test fresh
import subprocess
r = subprocess.run(
    ['docker', 'exec', 'terrablinds_db', 'psql', '-U', 'terrablinds', '-d', 'terrablinds_db',
     '-c', "UPDATE wa_conversation_state SET step='nuevo', producto=null, subtipo=null, "
           "nombre=null, email=null, direccion=null, medidas_lista='[]', completado=false, "
           "updated_at=NOW() WHERE phone='56998101891';"],
    capture_output=True, text=True)
print('\nReset test phone:', r.stdout.strip() or r.stderr.strip())
